version: '3'
services:
  node:
    image: node:14.7.0-alpine
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=debug
    volumes:
      - $PWD/web2-nodejs:/home/node/app
    ports:
      - 3000:3000
    command: node main.js